name: 'Register new tenant'
description: 'Register a new tenant on platelet'
author: 'Theo Cranmore'
inputs:
  awsAccessKeyId:
    required: true
    description: 'aws access key id'
  awsSecretAccessKey:
    required: true
    description: 'aws access key secret'
  awsRegion:
    required: true
    description: 'aws region'
  tenantApiUrl:
    required: true
    description: 'GraphQL API URL'
  tenantName:
    required: true
    description: 'name of the tenant'
  adminName:
    required: false
    description: 'name of the admin'
  adminEmail:
    required: false
    description: 'email address of the admin'
runs:
  using: 'node16'
  main: 'dist/index.js'
